---
- become: "{{ not ansible_check_mode }}"
  block:
    - name: "Increase standby delays on low/high battery charge to 24h/48h respectively"
      osx_pmset:
        on_battery:
          standbydelayhigh: "{{ 48*3600 }}"
          standbydelaylow: "{{ 24*3600 }}"
